puts "number_of_hours_worked_per_day = 10"
puts "number_of_days_worked_per_week = 5"
puts "number_of_weeks_in_TSA4 = 11"
puts "Travail : #{number_of_hours_worked_per_day * number_of_days_worked_per_week * number_of_weeks_in_TS4A}"
puts "Et en minutes ça fait : #{number_of_minutes_in_an_hour * number_of_hours_worked_per_day * number_of_days_worked_per_week * number_of_weeks_in_TS4A}"